repos:
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v1.1.0
      hooks:
        - id: conventional-pre-commit
          stages: [commit-msg]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.1
      hooks:
        - id: trailing-whitespace
        - id: check-merge-conflict
        - id: no-commit-to-branch
          args: [--branch, main, --branch, feature/.*, --branch, bug/.*]
